### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by olebowle**
Hi,

I don't know if you feel like the successor of Paul Bender maintaining eventlircd, but I feel OpenELEC is pretty alive these days. And as Google Code is in read-only mode now, I send this pull request to you guys. It fixes some error messages while compiling and the udev rules syntax.
There will be another pull request coming up for better systemd integration, once this one is merged.

Cheers,
olebowle

### CODE REVIEW

**Comment by olebowle** [comment]
Could someone please either reject or accept this PR? So I can either go on with spinning my own eventlircd fork or use yours?

Thank you!

**Comment by sraue** [comment]
@olebowle this repo here we created to save the work Paul has done while google code seems deprecated. i will check your PRs if you want and will add our seperate patches soon. if you want help with maintaining this repo here or mainatining one byself i would like to cooperate with you

**Comment by olebowle** [comment]
Hi Stephan,

I'm very interested in contributing here. I think the OpenELEC organization on Github is the best place for continuing Pauls work. That is why I opened up this PR.

I saw you have same important patches in your eventlircd package. I'd like to see them incorporated here as well - especially the one for kernel 4.4 compatibility. Let me know if you see an issue with my commits.

Cheers,
Ole

**Comment by sraue** [comment]
@olebowle thanks much. i just committed the patches i had. you are ok if i add the evmaps and rules for the various remotes we have included as-is?

**Comment by olebowle** [comment]
Please go ahead, so everyone can benefit from it.

**Pull request merged**
